name: zenn-qiita-actions
description: |
  Converts <zenn repository>/articles/*.md to <qiita repository>/public/*.md and pushes
  or
  Converts <qiita repository>/public/*.md to <zenn repository>/articles/*.md and pushes

inputs:
  zenn-path:
    description: Zenn repository path
    required: true
  qiita-path:
    description: Qiita repository path
    required: true
  push-to-path:
    description: Repository path to push (<inputs.zenn-path> or <inputs.qiita-path>)
    required: true
  commit-msg:
    description: Massage to commit to <inputs.push-to-path>
    required: true
  git-token:
    description: GitHub token to push to <inputs.push-to-path>
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Checkout repository for zenn-qiita-actions
      uses: actions/checkout@v4
      with:
        repository: r-dev95/zenn-qiita-actions
        path: zenn-qiita-actions
        ref: ${{ github.ref }}

    - name: Install dependencies
      run: |
        cd zenn-qiita-actions
        npm ci
      shell: bash

    - name: Run converter
      run: |
        if [ ${{ inputs.push-to-path }} = ${{ inputs.qiita-path }} ]; then
          node zenn-qiita-actions/dist/index.js ./${{ inputs.zenn-path }}/articles ./${{ inputs.qiita-path }}/public
        elif [ ${{ inputs.push-to-path }} = ${{ inputs.zenn-path }} ]; then
          echo "[Warning]: Not implemented Qiita to Zenn"
        else
          echo "[Error]: Ivalid inputs 'push-to-path'. (must be the same as 'zenn-path' or 'qiita-path')"
        fi
      shell: bash

    - name: Commit and push to repository
      run: |
        cd ${{ inputs.qiita-path }}
        git config user.name github-actions
        git config user.email actions@github.com
        git add public/
        git commit -m "${{ inputs.commit-msg }}" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${{ inputs.git-token }}@github.com/${{ github.repository_owner }}/${{ inputs.push-to-path }}.git
        git push origin HEAD
      shell: bash
