name: zenn-qiita-actions
description: |
  Converts <zenn repository>/articles/*.md to <qiita repository>/public/*.md and pushes
  or
  Converts <qiita repository>/public/*.md to <zenn repository>/articles/*.md and pushes

inputs:
  zenn-repo-name:
    description: Zenn repository name
    required: true
  qiita-repo-name:
    description: Qiita repository name
    required: true
  push-to-repo-name:
    description: Repository path to push (<inputs.zenn-repo-name> or <inputs.qiita-repo-name>)
    required: true
  commit-msg:
    description: Message to commit to <inputs.push-to-repo-name>
    required: true
  git-token:
    description: GitHub token to push to <inputs.push-to-repo-name>
    required: true
  json-path:
    description: GitHub token to push to <inputs.push-to-repo-name>
    required: false
    default: "dist/zenn-qiita-actions.json"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Checkout repository for zenn-qiita-actions
      uses: actions/checkout@v4
      with:
        repository: r-dev95/zenn-qiita-actions
        path: zenn-qiita-actions
        ref: ${{ github.ref }}

    - name: Install dependencies
      run: |
        echo "Install dependencies"
        cd zenn-qiita-actions
        npm ci
      shell: bash

    - name: Diff files
      run: |
        echo "Diff files"
        if [ ${{ inputs.push-to-repo-name == inputs.qiita-repo-name }} ]; then
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep "^articles/.*\.md$" > zenn-qiita-actions/diff.txt
        elif [ ${{ inputs.push-to-repo-name == inputs.zenn-repo-name }} ]; then
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep "^public/.*\.md$" > zenn-qiita-actions/diff.txt
        else
          echo "❌ [Failure] - Ivalid inputs 'push-to-repo-name'. (must be the same as 'zenn-repo-name' or 'qiita-repo-name')"
          exit 1
        fi
      shell: bash

    - name: Run converter
      if: success()
      run: |
        echo "Run converter"
        if [ ${{ inputs.push-to-repo-name == inputs.qiita-repo-name }} ]; then
          node zenn-qiita-actions/dist/index.js 0 ${{ inputs.zenn-repo-name }}/articles ${{ inputs.qiita-repo-name }}/public ${{ inputs.json-path }}
        else
          node zenn-qiita-actions/dist/index.js 1 ${{ inputs.qiita-repo-name }}/public ${{ inputs.zenn-repo-name }}/articles ${{ inputs.json-path }}
        fi
        if [[ -f "zenn-qiita-actions/diff.txt" ]]; then
          rm zenn-qiita-actions/diff.txt
      shell: bash

    - name: Commit and push to repository
      if: success()
      run: |
        echo "Commit and push to repository"
        cd ${{ inputs.push-to-repo-name }}
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        if [ ${{ inputs.push-to-repo-name == inputs.qiita-repo-name }} ]; then
          git add public/
        else
          git add articles/
        fi
        git commit -m "${{ inputs.commit-msg }}" || echo "Nothing to commit"
        git remote set-url origin https://x-access-token:${{ inputs.git-token }}@github.com/${{ github.repository_owner }}/${{ inputs.push-to-repo-name }}.git
        git push origin HEAD
      shell: bash
